### ISSUE TITLE
Concatenate Error

### ISSUE THREAD

**Issue by nrluna30** [krstphrrr/ingester_v3#1]
![37ConcatenateError](https://user-images.githubusercontent.com/71283749/138961874-3c897079-2bb3-4352-a52e-0a2985317148.PNG)

Above is a snippet of the error I'm getting.

**Comment by krstphrrr** [comment]
https://github.com/krstphrrr/ingester_v3/commit/e95e08ccad7b515f118d710a3386acd60f9c496d
